### PR TITLE
Added scripts for running PostgreSQL and Tomcat with Docker

### PR DESCRIPTION
**Pull request by lhanson**
These scripts and additional configuration profile allow a developer to run a PostgreSQL database and Tomcat instance in Docker containers, making it convenient to run artifact-listener locally without managing custom installations of those dependencies.

### CODE REVIEW

**Comment by lalmeras** [comment]
Great job, your work should help any person who wants to run artifact listener.

Can you work on the following issues I find before I merge your code:
* add in documentation that 5432 (for postgresql docker) 8080 (for tomcat docker) must not be used on host machine
* initialize both maven_artifact_notifier and maven_artifact_notifier_test users and databases in postgresql.sql and modify docker.properties appropriately so that maven.db.* and maven.test.db.* point to the right database, because _test database is used for unit tests and is dropped during test run

I'll work on my side on a way to run easily MavenArtifactNotifierInitFromExcelMain on the right database.

Thanks again.

**Comment by lhanson** [comment]
Sounds good. I think it would be ideal if `MavenArtifactNotifierInitFromExcelMain` could be run more generally without using Eclipse, maybe from Maven? The build is a bit IDE-specific at the moment.

**Comment by lalmeras** [comment]
Good advice. I target a maven-compliant way to run it.

**Comment by lalmeras** [comment]
Nice work; sorry for the delay.

**Pull request merged**
